//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFService.DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataquadEntities : DbContext
    {
        public DataquadEntities()
            : base("name=DataquadEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_race> tbl_race { get; set; }
        public virtual DbSet<tbl_userDetails> tbl_userDetails { get; set; }
        public virtual DbSet<tbl_userFilesCollection> tbl_userFilesCollection { get; set; }
        public virtual DbSet<tbl_userLoginDetails> tbl_userLoginDetails { get; set; }
        public virtual DbSet<tbl_userPersonalDetail> tbl_userPersonalDetail { get; set; }
        public virtual DbSet<tbl_userProfileImages> tbl_userProfileImages { get; set; }
    }
}
